local Upgrades = {
	Power = {
		{Level = 1, Multiplier = 1, Cost = 0},
		{Level = 2, Multiplier = 2, Cost = 500},
		{Level = 3, Multiplier = 5, Cost = 2500},
		{Level = 4, Multiplier = 10, Cost = 10000},
	},
	Coins = {
		{Level = 1, Multiplier = 1, Cost = 0},
		{Level = 2, Multiplier = 1.5, Cost = 1000},
		{Level = 3, Multiplier = 2, Cost = 5000},
		{Level = 4, Multiplier = 4, Cost = 20000},
	}
}

return Upgrades
